bidirectional:
    # obsolete
    baseline:
         randseg_raw_data_folder: ./data/fin-sme/bidirectional_baseline/
         randseg_cfg_file: ./config/fin2sme/bidirectional_baseline_cfg.sh
    own_huge:
         randseg_raw_data_folder: ./data/fin-sme/bidirectional_own_bt_huge
         randseg_cfg_file: ./config/fin2sme/bidirectional_own_bt_huge_cfg.sh
fin2sme:
    baseline:
         randseg_raw_data_folder: ./data/fin-sme/
         randseg_cfg_file: fin2sme_cfg.sh
    bt_nmt_all:
         randseg_raw_data_folder: ./data/fin-sme/nmt_bt
         randseg_cfg_file: ./config/fin2sme/nmt_bt_fin2sme_cfg.sh
    bt_rbmt_all:
         randseg_raw_data_folder: ./data/fin-sme/rbmt_bt
         randseg_cfg_file: ./config/fin2sme/rbmt_bt_fin2sme_cfg.sh
    bt_nmt_clean:
         randseg_cfg_file: ./config/fin2sme/clean_nmt_bt_fin2sme_cfg.sh
         randseg_raw_data_folder: ./data/fin-sme/clean_nmt_bt
    bt_rbmt_clean:
         randseg_cfg_file: ./config/fin2sme/clean_rbmt_bt_fin2sme_cfg.sh
         randseg_raw_data_folder: ./data/fin-sme/clean_rbmt_bt
    bt_nmt_all_rbmt_all:
         randseg_cfg_file: ./config/fin2sme/rbmt_nmt_bt_fin2sme_cfg.sh
         randseg_raw_data_folder: ./data/fin-sme/rbmt_nmt_bt
    bt_nmt_clean_rbmt_clean:
         randseg_cfg_file: ./config/fin2sme/clean_rbmt_nmt_bt_fin2sme_cfg.sh
         randseg_raw_data_folder: ./data/fin-sme/clean_rbmt_nmt_bt
    bt_nmt_clean_rbmt_all:
         randseg_cfg_file: ./config/fin2sme/clean_nmt_all_rbmt_bt_fin2sme_cfg.sh
         randseg_raw_data_folder: ./data/fin-sme/clean_nmt_all_rbmt_bt
    own_huge2:
         randseg_cfg_file: ./config/fin2sme/own_bt_huge2_fin2sme_cfg.sh
         randseg_raw_data_folder: ./data/fin-sme/own_bt_huge2_fin2sme
    own_huge:
         randseg_raw_data_folder: ./data/fin-sme/own_bt_huge
         randseg_cfg_file: ./config/fin2sme/joint_own_bt_huge_fin2sme_cfg.sh
    own:
         randseg_raw_data_folder: ./data/fin-sme/own_bt_onceonly
         randseg_cfg_file: ./config/fin2sme/joint_own_bt_fin2sme_cfg.sh
    own_beam1:
         randseg_cfg_file: ./config/fin2sme/own_bt_beam1_fin2sme_cfg.sh
         randseg_raw_data_folder: ./data/fin-sme/own_bt_beam1
    own_beam1_huge:
         randseg_cfg_file: ./config/fin2sme/own_bt_beam1_huge_fin2sme_cfg.sh
         randseg_raw_data_folder: ./data/fin-sme/own_bt_beam1_plus_huge
sme2fin:
    baseline:
         randseg_raw_data_folder: ./data/fin-sme/
         randseg_cfg_file: sme2fin_cfg.sh
    bt_nmt_all:
         randseg_raw_data_folder: ./data/fin-sme/nmt_bt
         randseg_cfg_file: ./config/sme2fin/nmt_bt_sme2fin_cfg.sh
    bt_rbmt_all:
         randseg_raw_data_folder: ./data/fin-sme/rbmt_bt
         randseg_cfg_file: ./config/sme2fin/rbmt_bt_sme2fin_cfg.sh
    bt_nmt_clean:
         randseg_cfg_file: ./config/sme2fin/clean_nmt_bt_sme2fin_cfg.sh
         randseg_raw_data_folder: ./data/fin-sme/clean_nmt_bt
    bt_rbmt_clean:
         randseg_cfg_file: ./config/sme2fin/clean_rbmt_bt_sme2fin_cfg.sh
         randseg_raw_data_folder: ./data/fin-sme/clean_rbmt_bt
    bt_nmt_all_rbmt_all:
         randseg_cfg_file: ./config/sme2fin/rbmt_nmt_bt_sme2fin_cfg.sh
         randseg_raw_data_folder: ./data/fin-sme/rbmt_nmt_bt
    bt_nmt_clean_rbmt_clean:
         randseg_cfg_file: ./config/sme2fin/clean_rbmt_nmt_bt_sme2fin_cfg.sh
         randseg_raw_data_folder: ./data/fin-sme/clean_rbmt_nmt_bt
    bt_nmt_clean_rbmt_all:
         randseg_cfg_file: ./config/sme2fin/clean_nmt_all_rbmt_bt_sme2fin_cfg.sh
         randseg_raw_data_folder: ./data/fin-sme/clean_nmt_all_rbmt_bt
    own_huge2:
         randseg_cfg_file: ./config/sme2fin/own_bt_huge2_sme2fin_cfg.sh
         randseg_raw_data_folder: ./data/fin-sme/own_bt_huge2_sme2fin
    own_huge:
         randseg_raw_data_folder: ./data/fin-sme/own_bt_huge
         randseg_cfg_file: ./config/sme2fin/joint_own_bt_huge_sme2fin_cfg.sh
    own:
         randseg_raw_data_folder: ./data/fin-sme/own_bt_onceonly
         randseg_cfg_file: ./config/sme2fin/joint_own_bt_sme2fin_cfg.sh
    own_beam1:
         randseg_cfg_file: ./config/sme2fin/own_bt_beam1_sme2fin_cfg.sh
         randseg_raw_data_folder: ./data/fin-sme/own_bt_beam1
    own_beam1_huge:
         randseg_cfg_file: ./config/sme2fin/own_bt_beam1_huge_sme2fin_cfg.sh
         randseg_raw_data_folder: ./data/fin-sme/own_bt_beam1_plus_huge
eng2iku:
    baseline:
         randseg_cfg_file: ./config/eng2iku/joint_baseline_eng2iku_cfg.sh
         randseg_raw_data_folder: ./data/eng-iku/hansard-newstest
iku2eng:
    baseline:
         randseg_cfg_file: ./config/iku2eng/joint_baseline_iku2eng_cfg.sh
         randseg_raw_data_folder: ./data/iku-eng/hansard-newstest
