# Inuktitut
- id: hansard-eng-iku
  langs: eng-iku
  desc: "English <-> Inuktitut, Hansard data"
  train:
    - NRC_CA-nunavut_hansard_train-3-iku-eng
  dev:
    - NRC_CA-nunavut_hansard_dev-3-iku-eng
  test:
    - NRC_CA-nunavut_hansard_test-3-iku-eng

- id: hansard-newstest-eng-iku
  langs: eng-iku
  desc: "English -> Inuktitut, Hansard train / WMT20 dev and test"
  train:
    - NRC_CA-nunavut_hansard_train-3-iku-eng
  dev:
    - Statmt-newsdev_eniu-2020-eng-iku
  test:
    - Statmt-newstest_eniu-2020-eng-iku

- id: hansard-newstest-iku-eng
  langs: iku-eng
  desc: "Inuktitut -> English, Hansard train / WMT20 dev and test"
  train:
    - NRC_CA-nunavut_hansard_train-3-iku-eng
  dev:
    - Statmt-newsdev_iuen-2020-iku-eng
  test:
    - Statmt-newstest_iuen-2020-iku-eng
 
