#!/usr/bin/env python

import re

import yaml
import click


@click.command()
@click.argument("local_command")
@click.argument("yaml_file")
def create_command(local_command, yaml_file):
    args = parse_yaml_to_args(yaml_file)
    click.echo(f"{local_command} {args}")


def parse_yaml_to_args(yaml_file, prefix=""):
    # Read YAML file and parse it into a string of the form
    # "--key=value --key2=value2" etc.
    # If any argument is 'true' or 'false', it should be included as a flag
    with open(yaml_file, "r") as file:
        data = yaml.safe_load(file)

    args = ""

    for key, value in data.items():
        if isinstance(value, bool):
            args += f"--{prefix}{key} "
        # in case of tuple of floats, stringify it
        elif isinstance(value, str) and re.match(r"\(\d+\.\d+,\s*\d+\.\d+\)", value):
            args += f"--{prefix}{key} '{value}' "
        else:
            args += f"--{prefix}{key} {value} "

    return args.strip()


if __name__ == "__main__":
    create_command()
